"use client";

import { useState } from "react";
import { Clock3, ExternalLink, Play, QrCode, Radio, Square, Users, X } from "lucide-react";
import Link from "next/link";

export type SessionClass = { room: string; classCode: string; time: string; instructors: string[]; target: number; submitted: number; status: string; qr: string; surveyUrl: string };

export function SessionOperatorPanel({ classes }: { classes: SessionClass[] }) {
  const [selectedCode, setSelectedCode] = useState(classes[0]?.classCode ?? "");
  const [zoom, setZoom] = useState(false);
  const selected = classes.find((item) => item.classCode === selectedCode) ?? classes[0];
  if (!selected) return null;
  return <>
    <section className="card session-selector"><div><div className="teacher-kicker">현장 운영요원</div><h2 style={{ margin: "5px 0 4px" }}>평가할 반을 선택하세요</h2><p style={{ margin: 0, color: "#65758a", fontSize: 13 }}>선택한 반의 강사와 QR만 현장 화면에 표시됩니다.</p></div><select className="class-picker" value={selectedCode} onChange={(event) => setSelectedCode(event.target.value)} aria-label="평가 반 선택">{classes.map((item) => <option key={item.classCode} value={item.classCode}>{item.classCode} · {item.room}호 · {item.time}</option>)}</select></section>
    <section className="grid-2" style={{ gridTemplateColumns: "minmax(360px,.85fr) 1.4fr" }}>
      <div className="card qr-session-card"><div className="session-heading"><div><span className={`status ${selected.status === "ACTIVE" ? "NORMAL" : "INSUFFICIENT"}`}><Radio size={11} /> {selected.status === "ACTIVE" ? "진행 중" : "시작 대기"}</span><h2>{selected.classCode} · {selected.room}호</h2><div className="live-meta">{selected.instructors.join(" · ")} 강사</div></div><div className="session-time"><Clock3 size={14} /> {selected.time}</div></div><button className="qr-only-button" type="button" onClick={() => setZoom(true)} aria-label="QR 크게 보기"><img src={selected.qr} alt={`${selected.classCode} 강의평가 QR 코드`} className="qr-image" /></button><p className="qr-help">QR 이미지만 클릭하면 크게 볼 수 있습니다.<br />학생에게 QR을 보여준 뒤 평가를 시작하세요.</p><Link href={selected.surveyUrl} target="_blank" className="btn btn-secondary full-button">학생 화면 미리보기 <ExternalLink size={15} /></Link><button className="btn btn-danger full-button"><Square size={14} /> 평가 종료</button></div>
      <div className="card"><div className="panel-head"><h2>제출 현황</h2><span>선택한 {selected.classCode}</span></div><div style={{ padding: "0 22px 20px" }}><div className="stat-grid session-stats"><div className="stat"><div className="stat-label">조사 대상</div><div className="stat-value">{selected.target}명</div></div><div className="stat"><div className="stat-label">완료</div><div className="stat-value" style={{ color: "#25a67a" }}>{selected.submitted}명</div></div><div className="stat"><div className="stat-label">참여율</div><div className="stat-value">{(selected.submitted / selected.target * 100).toFixed(1)}%</div></div></div><div style={{ display: "grid", gap: 12 }}>{selected.instructors.map((name, index) => <div key={name} className="instructor-progress"><div><strong>{name} 강사</strong><div className="live-meta">유효 응답 · 익명 저장</div></div><div style={{ fontWeight: 800 }}>{Math.max(selected.submitted - index, 0)} / {selected.target}</div></div>)}</div><div className="verification-note"><strong>대상 인원 검증</strong><br />KGAS 당일 출결과 조사자가 입력한 대상 인원이 일치합니다.</div></div></div>
    </section><section className="card table-card"><div className="panel-head"><h2>오늘의 방문 일정</h2><span>{classes.length}개 반</span></div><table className="data-table"><thead><tr><th>시간</th><th>반 / 강의실</th><th>평가 대상 강사</th><th>대상</th><th>제출</th><th>상태</th><th /></tr></thead><tbody>{classes.map((item) => <tr key={item.classCode}><td><strong>{item.time}</strong></td><td>{item.classCode} · {item.room}호</td><td>{item.instructors.join(", ")}</td><td><Users size={13} /> {item.target}명</td><td>{item.submitted}명</td><td><span className={`status ${item.status === "ACTIVE" ? "NORMAL" : "INSUFFICIENT"}`}>{item.status === "ACTIVE" ? "진행 중" : "시작 대기"}</span></td><td><button className="btn btn-secondary" style={{ padding: "7px 10px" }} onClick={() => setSelectedCode(item.classCode)}><QrCode size={14} /> 선택</button></td></tr>)}</tbody></table></section>
    {zoom && <div className="qr-modal" role="dialog" aria-modal="true" aria-label="확대된 QR 코드" onClick={() => setZoom(false)}><div className="qr-modal-card" onClick={(event) => event.stopPropagation()}><button className="qr-modal-close" onClick={() => setZoom(false)} aria-label="닫기"><X size={19} /></button><img src={selected.qr} alt="확대된 강의평가 QR 코드" /><strong>{selected.classCode} · {selected.room}호</strong><span>화면을 클릭하면 닫힙니다.</span></div></div>}
  </>;
}
