import { hash } from "@node-rs/argon2";
import { eq } from "drizzle-orm";
import { getDb } from "../lib/db";
import { admins, classes, instructors, questionnaireVersions, teachingAssignments, terms } from "./schema";
import { surveyQuestions } from "../lib/demo-data";

async function seed(){const db=getDb();const email=process.env.ADMIN_EMAIL??"admin@kmu.ac.kr";const existing=await db.select().from(admins).where(eq(admins.email,email)).limit(1);if(!existing.length)await db.insert(admins).values({email,name:"김관리",passwordHash:await hash(process.env.ADMIN_PASSWORD??"demo-admin"),role:"SYSTEM_ADMIN"});let [term]=await db.select().from(terms).where(eq(terms.code,"2026-SUMMER")).limit(1);if(!term)[term]=await db.insert(terms).values({code:"2026-SUMMER",name:"2026년 여름학기",startsAt:new Date("2026-06-01T00:00:00+09:00"),endsAt:new Date("2026-08-31T23:59:59+09:00"),active:true}).returning();const questionnaires=await db.select().from(questionnaireVersions).where(eq(questionnaireVersions.termId,term.id)).limit(1);if(!questionnaires.length)await db.insert(questionnaireVersions).values({termId:term.id,version:1,title:"기본 강의평가",questions:surveyQuestions});let [klass]=await db.select().from(classes).where(and(eq(classes.termId,term.id),eq(classes.code,"1"))).limit(1);if(!klass)[klass]=await db.insert(classes).values({termId:term.id,code:"1",room:"134",scheduledAt:new Date("2026-08-05T10:00:00+09:00"),scheduledEndAt:new Date("2026-08-05T10:05:00+09:00"),eligibleCount:18}).returning();for(const [position,name] of ["정재영","안혜진"].entries()){let [instructor]=await db.select().from(instructors).where(eq(instructors.name,name)).limit(1);if(!instructor)[instructor]=await db.insert(instructors).values({name}).returning();await db.insert(teachingAssignments).values({classId:klass.id,instructorId:instructor.id,position:position+1}).onConflictDoNothing();}console.log("Seed complete");process.exit(0)}
import { and } from "drizzle-orm";
seed().catch(error=>{console.error(error);process.exit(1)});
